export const translations = {
  en: {
    title: 'Command Center',
    subtitleGit: 'Transform tasks into git workflows instantly',
    subtitleNode: 'Manage packages and scripts without memorizing commands',
    subtitleDocker: 'Spin up containers and services with a single click',
    wfNew: 'New Branch',
    wfRecreate: 'Recreate Branch',
    lblTask: 'Task Title / Branch',
    lblBase: 'Base Branch',
    lblType: 'Task Type',
    lblTarget: 'Target Branch',
    lblCommit: 'Commit Message',
    lblWorkflow: 'Workflow Commands',
    btnCopy: 'Copy',
    btnCopySeq: 'Copy Sequence',
    copied: 'Copied!',
    cmdCreate: 'Create Branch',
    cmdStage: 'Stage Changes',
    cmdStatus: 'Check Status',
    cmdCommit: 'Commit Task',
    cmdPush: 'Push to Origin',
    cmdExit: 'Exit Branch',
    cmdDelete: 'Delete Local',
    cmdDeleteRemote: 'Delete Remote',
    cmdPull: 'Pull Latest',
    cmdRecreate: 'Recreate Branch',
    cmdPushNew: 'Push Fresh Branch',
    cmdSync: 'Pro/Team Sync',
    manualNotice: 'Manual mode: Task type only affects commit message',
    nodeMgr: 'Package Manager',
    nodeInstall: 'Install Packages',
    nodeType: 'Type',
    nodeQuick: 'Quick NPM Actions',
    nodeOutput: 'Generated Commands',
    dockerImg: 'Image Name',
    dockerPort: 'Ports (Host:Container)',
    dockerCompose: 'Docker Compose',
    dockerQuick: 'Quick Management',
    dockerOutput: 'Generated Commands',
    dockerVault: 'Docker Vault (Cheat Sheet)',
    dockerSearch: 'Search command...',
    dockerService: 'Service Name',
    dockerFile: 'Compose File',
    lblFullPreview: 'Full Workflow Preview',
    lblGitVault: 'Git Vault (Quick Actions)',
    lblNodeVault: 'Node Vault (Toolbox)',
    searchPlaceholder: 'Search commands...',
    warningLong: 'Branch name is quite long!',
    warningChars: 'The branch contains unusual characters.',
    btnReset: 'Reset to auto',
    listView: 'List View',
    terminalView: 'Terminal View',
    typeFeature: 'Feature',
    typeFix: 'Fix',
    typeHotfix: 'Hotfix',
    typeChore: 'Chore',
    typeDocs: 'Docs',
    typeRefactor: 'Refactor',
    lblFavsVault: 'My Favorites',
    subtitleFavs: 'Your most used commands in one place',
    lblPriority: 'PRIORITY',
    txtNoFavs: 'No favorites yet. Star some commands to see them here!'
  },
  es: {
    title: 'Centro de Mandos',
    subtitleGit: 'Transforma tareas en flujos de git al instante',
    subtitleNode: 'Gestiona paquetes y scripts sin memorizar comandos',
    subtitleDocker: 'Levanta contenedores y servicios con un solo clic',
    wfNew: 'Nueva Rama',
    wfRecreate: 'Recrear Rama',
    lblTask: 'Título de Tarea / Rama',
    lblBase: 'Rama Base',
    lblType: 'Tipo de Tarea',
    lblTarget: 'Rama Generada',
    lblCommit: 'Mensaje de Commit',
    lblWorkflow: 'Comandos del Flujo',
    btnCopy: 'Copiar',
    btnCopySeq: 'Copiar Secuencia',
    copied: '¡Copiado!',
    cmdCreate: 'Crear Rama',
    cmdStage: 'Preparar Cambios',
    cmdStatus: 'Ver Estado',
    cmdCommit: 'Confirmar Tarea (Commit)',
    cmdPush: 'Subir a Origin',
    cmdExit: 'Salir de la Rama',
    cmdDelete: 'Borrar Rama Local',
    cmdDeleteRemote: 'Borrar Rama Remota',
    cmdPull: 'Bajar cambios (Pull)',
    cmdRecreate: 'Recrear Rama',
    cmdPushNew: 'Subir nueva rama',
    cmdSync: 'Sincronización Pro',
    manualNotice: 'Modo manual: El tipo de tarea solo afecta al commit',
    nodeMgr: 'Gestor de Paquetes',
    nodeInstall: 'Instalar Paquetes',
    nodeType: 'Tipo',
    nodeQuick: 'Acciones Rápidas NPM',
    nodeOutput: 'Comandos Generados',
    dockerImg: 'Nombre de Imagen',
    dockerPort: 'Puertos (Host:Contenedor)',
    dockerCompose: 'Docker Compose',
    dockerQuick: 'Gestión Rápida',
    dockerOutput: 'Comandos Generados',
    dockerVault: 'Bóveda de Docker (Guía Rápida)',
    dockerSearch: 'Buscar comando...',
    dockerService: 'Nombre del Servicio',
    dockerFile: 'Archivo Compose',
    lblFullPreview: 'Vista Previa del Flujo Completo',
    lblGitVault: 'Bóveda de Git (Acciones Rápidas)',
    lblNodeVault: 'Bóveda de Node (Herramientas)',
    searchPlaceholder: 'Buscar comandos...',
    warningLong: '¡La rama es muy larga!',
    warningChars: 'La rama contiene caracteres inusuales.',
    btnReset: 'Volver a automático',
    listView: 'Vista Lista',
    terminalView: 'Modo Terminal',
    typeFeature: 'Feature',
    typeFix: 'Fix',
    typeHotfix: 'Hotfix',
    typeChore: 'Chore',
    typeDocs: 'Docs',
    typeRefactor: 'Refactor',
    lblFavsVault: 'Mis Favoritos',
    subtitleFavs: 'Tus comandos más usados en un solo lugar',
    lblPriority: 'PRIORIDAD',
    txtNoFavs: 'Aún no tienes favoritos. ¡Marca algunos comandos para verlos aquí!'
  }
};

export const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'is', 'if', 'then', 'else', 'when', 'at', 'from', 'by', 'for', 'with', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', 'should', 'now', 'to', 'that', 'this', 'these', 'those', 'am', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing',
  'el', 'la', 'los', 'las', 'un', 'una', 'unos', 'unas', 'y', 'o', 'pero', 'con', 'para', 'por', 'de', 'del', 'al', 'en', 'sobre', 'entre', 'hacia', 'hasta', 'desde', 'durante', 'contra', 'que', 'este', 'esta', 'estos', 'estas', 'ese', 'esa', 'esos', 'esas', 'mi', 'tu', 'su', 'mis', 'tus', 'sus', 'como', 'más', 'pero', 'sus', 'le', 'ya', 'este', 'sí', 'porque', 'esta', 'entre', 'cuando', 'muy', 'sin', 'sobre', 'también', 'me', 'hasta', 'hay', 'donde', 'quien', 'desde', 'todo', 'nos', 'durante', 'todos', 'uno', 'les', 'ni', 'contra', 'otros', 'ese', 'eso', 'ante', 'ellos', 'esto', 'mí', 'antes', 'algunos', 'qué', 'unos', 'yo', 'otro', 'otras', 'otra', 'él', 'tanto', 'esa', 'estos', 'mucho', 'quienes', 'nada', 'si'
]);

export const TECH_WHITELIST = new Set([
  'api', 'ui', 'ux', 'db', 'auth', 'login', 'url', 'id', 'v1', 'v2', 'css', 'js', 'html', 'json', 'sql', 'rest', 'git', 'fe', 'be',
  'bd', 'servidor', 'server', 'error', 'falla', 'fail', 'inicio', 'sesion', 'token', 'endpoint', 'ruta', 'route', 'modelo', 'model', 'vista', 'view', 'controlador', 'controller',
  'loader', 'componente', 'component', 'modulo', 'module', 'servicio', 'service', 'hook', 'store', 'state', 'reusable'
]);

export const ACTION_VERBS = new Set([
  'add', 'fix', 'update', 'remove', 'delete', 'refactor', 'create', 'patch', 'bug', 'error', 'show', 'hide',
  'agregar', 'anadir', 'quitar', 'eliminar', 'borrar', 'corregir', 'arreglar', 'actualizar', 'mejorar', 'crear', 'refactorizar', 'mostrar', 'ocultar',
  'unificar', 'unify', 'reemplazar', 'replace', 'estandarizar', 'standardize', 'migrar', 'migrate', 'implementar', 'implement'
]);
